name = Search Menus
description = A simple 2 column grid layout for search menus
template = search-menus-layout

; Regions
regions[header_left] = Header Left
regions[header_right] = Header Right
regions[sidebar] = Sidebar
regions[content] = Content
regions[footer] = Footer

; Styles
stylesheets[all][] = css/layouts/search-menus/search-menus.layout.css
stylesheets[all][] = css/layouts/search-menus/search-menus.layout.no-query.css
stylesheets[all][] = css/layouts/search-menus/splatnom-search-menus.layout.css

