name = User Account
description = A simple 1 column grid layout for the user account page (register, login, request password)
template = user-account-layout

; Regions
regions[header_left] = Header Left
regions[header_right] = Header Right
regions[content] = Content
regions[footer] = Footer

; Styles
stylesheets[all][] = css/layouts/user-account/user-account.layout.css
stylesheets[all][] = css/layouts/user-account/user-account.layout.no-query.css
stylesheets[all][] = css/layouts/user-account/splatnom-user-account.layout.css

