name = Restaurant Menu
description = A simple 2 column grid layout for restaurant menu
template = restaurant-menu-layout

; Regions
regions[header_left] = Header Left
regions[header_right] = Header Right
regions[sidebar] = Sidebar
regions[content] = Content
regions[footer] = Footer

; Styles
stylesheets[all][] = css/layouts/restaurant-menu/restaurant-menu.layout.css
stylesheets[all][] = css/layouts/restaurant-menu/restaurant-menu.layout.no-query.css
stylesheets[all][] = css/layouts/restaurant-menu/splatnom-restaurant-menu.layout.css

