name = Default Splatnom Layout
description = A simple 2 column grid layout for a default splatnom layout
template = default-splatnom-layout

; Regions
regions[header_left] = Header Left
regions[header_right] = Header Right
regions[sidebar] = Sidebar
regions[content] = Content
regions[footer] = Footer

; Styles
stylesheets[all][] = css/layouts/default-splatnom/default-splatnom.layout.css
stylesheets[all][] = css/layouts/default-splatnom/default-splatnom.layout.no-query.css
stylesheets[all][] = css/layouts/default-splatnom/splatnom-default-splatnom.layout.css

