name = User
description = A simple 1 column grid layout for the user pages
template = user-layout

; Regions
regions[header_left] = Header Left
regions[header_right] = Header Right
regions[content] = Content
regions[footer] = Footer

; Styles
stylesheets[all][] = css/layouts/user/user.layout.css
stylesheets[all][] = css/layouts/user/user.layout.no-query.css
stylesheets[all][] = css/layouts/user/splatnom-user.layout.css

