name = User New
description = A simple 1 column grid layout for new user page
template = user-new-layout

; Regions
regions[header_left] = Header Left
regions[header_right] = Header Right
regions[content] = Content
regions[footer] = Footer

; Styles
stylesheets[all][] = css/layouts/user-new/user-new.layout.css
stylesheets[all][] = css/layouts/user-new/user-new.layout.no-query.css
stylesheets[all][] = css/layouts/user-new/splatnom-user-new.layout.css

