name = Home
description = A simple 1 column grid layout for the homepage
template = home-layout

; Regions
regions[header_left] = Header Left
regions[header_right] = Header Right
regions[content] = Content
regions[footer] = Footer

; Styles
stylesheets[all][] = css/layouts/home/home.layout.css
stylesheets[all][] = css/layouts/home/home.layout.no-query.css
stylesheets[all][] = css/layouts/home/splatnom-home.layout.css

