name = User Pages
description = A simple 1 column grid layout for user pages
template = user-pages-layout

; Regions
regions[header_left] = Header Left
regions[header_right] = Header Right
regions[content] = Content
regions[footer] = Footer

; Styles
stylesheets[all][] = css/layouts/user-pages/user-pages.layout.css
stylesheets[all][] = css/layouts/user-pages/user-pages.layout.no-query.css
stylesheets[all][] = css/layouts/user-pages/splatnom-user-pages.layout.css

